services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
    command: python app.py
    restart: unless-stopped

volumes:
  data:
